### PR TITLE
Some edits for Preface.

### PR DESCRIPTION
**Pull request by cryptorick**
Details.
- s/enroll to/enroll at/
- s/kill/eliminate/
- s/goodness/any value/
  
  You originally had "any value" which is better IMO.  Also, just
  "value" would work.
- Re-worked "examples and exercises" part.
- s/in the industry/in industry/
- s/that/who/ (where it pertains to people)
- s/to college/to university/
  
  You originally had "to the university", but prefer "to university"
  (i.e no "the").
- In section "Reporting bugs", re-worked the "the quality of this text
  may be questionable" part.  Most English-speaking people use the
  word "questionable" usually to mean something like "spurious in
  nature" and I don't think you wanted/meant that. :)
  
  For instance, the first entry for the word "questionable" in the
  Random House Dictionary is "of doubtful propriety, honesty,
  morality, respectability, etc."
  (http://dictionary.reference.com/browse/questionable)
- Other small changes.

### CODE REVIEW

**Comment by panicz** [comment]
Thanks for this work. I like the way you reworked the part regarding the examples, and I think it is much clearer now.
With regard to the "Reporting bugs" part, I wrote it mainly to warn readers that it is not a very serious book. I'm not sure how the word "pamphlet" is perceived in English-speaking countries -- in Polish, in addition to "an unbound book", it is synonymous to "lampoon", or "a text of dubious quality that attacks someone", and my original intent (which -- as I see it now -- didn't work out) was to make it appear as a self-aware text of dubious quality.
I thought that I could allow myself for that, because I believe that after all, the text was a little better than it claimed to be.

**Comment by cryptorick** [comment]
Hehe, that's very interesting about the meaning of "pamphlet" in Polish.  I think the English meaning hasn't (yet) reached that level of "dubiousness".  But who knows?  Perhaps it is in our future?  Oh well, just give us enough time.  :)

BTW, please feel free to use any portion of this commit -- which also means free free to modify or discard what you don't agree with.  I will not be offended if you reject all or part of it; and likewise I did not intend that this submission pressure you on any changes.  All are merely suggestions.  Thank you for sharing your work.  I look forward to reading the rest.

**Comment by panicz** [comment]
Thanks, I will surely merge your changes during the upcoming week (I need some time to regenerate the PDF document to make it available)

Regarding the word "pamphlet", when I was chosing the title, I've searched the web for the collocation "A Pamphlet against X", and one title appeared: "Pamphlet Against Anthologies" by Laura Jackson. I didn't have a possibility to read it though, because it is unavailable in my library, but I trusted that its author's intent was similar.

Anyway, I hope you enjoy further reading and suggest some more fixes :)

**Comment by drcz** [comment]
concerning second detail: i think "kill" is way funnier than "eliminate"... what would you both say about "violently destroy"?

**Comment by panicz** [comment]
I merged the pull request, but I left the "Reporting bug" section as it was. Also, as a means of compromise, I chose "to violently eliminate", because you can't destroy something that's already broken ;]

**Pull request merged**
